name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy_check:
    strategy:
      matrix:
        crate:
          - clicky-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy --all-features --package ${{ matrix.crate }} -- -D warnings
